################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
weight = 1
[cn]
languageName = "简体中文"
languageCode = "zh-cn"
weight = 2
[iD]
languageName = "Indonesian"
languageCode = "id-id"
weight = 3

